version: '3.8'

services:
  pack-service:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./config.docker.toml:/go/src/app/cmd/app/config.toml

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - pack-service

