### Calculate packs
POST http://localhost:8080/v1/pack/calc
Accept: application/json
Content-Type: application/json

{
  "pack_sizes": [
    250,
    500,
    1000,
    2000,
    5000
  ],
  "total_amount": 12001
}
